"""Gate 1a calibration sheet.

Every element exists to convert a subjective "this looks a bit off" into a
measurable number about THIS printer. Without it, a disappointing shirt cannot be
attributed to the file, the RIP, the ink or the press.

Generated by the same sizing and compositing path as the production artwork, so
it measures the pipeline we actually ship rather than a parallel one.

Nothing here defines a tolerance. Tolerances come back from the physical sample.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

from ..core.compose import TRANSPARENT, WHITE, load_font, missing_glyphs, render_line

# Plausible brand-red candidates spanning the range typical brand reds occupy.
# NONE of these is claimed to be the brand red, which remains unknown and must be
# supplied from authoritative assets. The sweep characterises how this printer
# reproduces reds as a family, so the real value can be placed against measured
# behaviour once known.
RED_SWEEP = [
    ("#FF0000", (255, 0, 0)),
    ("#E30613", (227, 6, 19)),
    ("#D0021B", (208, 2, 27)),
    ("#C8102E", (200, 16, 46)),
    ("#B71C1C", (183, 28, 28)),
    ("#A6192E", (166, 25, 46)),
]

GREY_STEPS = [0, 10, 25, 50, 75, 90, 100]
ALPHA_STEPS = [10, 25, 50, 75, 90, 100]
STROKE_LADDER_MM = [0.25, 0.5, 1.0, 2.0, 3.0, 4.0]
TEXT_LADDER_PT = [6, 8, 10, 12, 16]
NEGATIVE_SPACE_MM = [0.25, 0.5, 1.0, 1.5, 2.0, 3.0]

# Proprietary terminology appears here as exact strings ONLY — string-fidelity
# probes measuring hyphen and capitalisation survival at print scale. No
# illustration, symbol or visual interpretation accompanies them, because their
# meanings have not been supplied and must not be invented (D-16).
IP_PROBE_STRING = "N-Codes  E-Codes  Inner DNA"


@dataclass
class CalibrationResult:
    image: Image.Image
    width_mm: float
    height_mm: float
    dpi: float
    elements: list[str] = field(default_factory=list)
    rendered_strings: list[str] = field(default_factory=list)
    missing_glyph_chars: list[str] = field(default_factory=list)
    regions: dict = field(default_factory=dict)

    @property
    def rgba(self) -> np.ndarray:
        return np.asarray(self.image.convert("RGBA"))


def _mm(value: float, dpi: float) -> int:
    return round(value / 25.4 * dpi)


def _pt(value: float, dpi: float) -> int:
    return max(1, round(value / 72.0 * dpi))


def build_calibration_sheet(font_path: str | Path, dpi: float = 300.0,
                            width_mm: float = 200.0) -> CalibrationResult:
    font_path = str(font_path)
    W = _mm(width_mm, dpi)
    margin = _mm(8, dpi)
    canvas = Image.new("RGBA", (W, _mm(420, dpi)), TRANSPARENT)
    draw = ImageDraw.Draw(canvas)

    label_px = _pt(9, dpi)
    head_px = _pt(13, dpi)
    elements: list[str] = []
    rendered: list[str] = []
    regions: dict = {}

    def label(text: str, x: int, y: int, size_px: int = label_px) -> int:
        img = render_line(font_path, text, size_px, 0)
        canvas.alpha_composite(img, (x, y))
        rendered.append(text)
        return img.height

    def heading(text: str, y: int) -> int:
        h = label(text, margin, y, head_px)
        return y + h + _mm(2.5, dpi)

    y = margin

    # --- title and orientation ------------------------------------------------
    title_h = label("DTF CALIBRATION v1", margin, y, _pt(18, dpi))
    ori = render_line(font_path, "R", _pt(30, dpi), 0)
    canvas.alpha_composite(ori, (W - margin - ori.width, y))
    label("ORIENT", W - margin - ori.width - _mm(20, dpi), y + _mm(3, dpi))
    elements.append("orientation_marker_R")
    y += max(title_h, ori.height) + _mm(4, dpi)
    y = heading("1. RED FAMILY SWEEP  (brand red UNKNOWN - none of these is claimed as brand red)", y)

    # --- red sweep ------------------------------------------------------------
    pw, ph = _mm(28, dpi), _mm(18, dpi)
    gap = _mm(2, dpi)
    for i, (hexname, rgb) in enumerate(RED_SWEEP):
        x = margin + i * (pw + gap)
        draw.rectangle([x, y, x + pw - 1, y + ph - 1], fill=(*rgb, 255))
        label(hexname, x, y + ph + _mm(1, dpi))
        regions.setdefault("red_family_sweep", []).append(
            {"hex": hexname, "rgb": list(rgb), "x": x, "y": y, "w": pw, "h": ph})
    elements.append("red_family_sweep")
    y += ph + _mm(7, dpi)
    y = heading("2. GREYSCALE WEDGE", y)

    for i, pct in enumerate(GREY_STEPS):
        v = round(255 * pct / 100)
        x = margin + i * (pw + gap)
        draw.rectangle([x, y, x + pw - 1, y + ph - 1], fill=(v, v, v, 255))
        label(f"{pct}%", x, y + ph + _mm(1, dpi))
    elements.append("greyscale_wedge")
    y += ph + _mm(7, dpi)
    y = heading("3. ALPHA STEP WEDGE  (white at partial alpha - underbase haze test)", y)

    # --- alpha step wedge -----------------------------------------------------
    for i, pct in enumerate(ALPHA_STEPS):
        a = round(255 * pct / 100)
        x = margin + i * (pw + gap)
        draw.rectangle([x, y, x + pw - 1, y + ph - 1], fill=(255, 255, 255, a))
        label(f"a{pct}%", x, y + ph + _mm(1, dpi))
        regions.setdefault("alpha_step_wedge", []).append(
            {"pct": pct, "alpha": a, "x": x, "y": y, "w": pw, "h": ph})
    elements.append("alpha_step_wedge")
    y += ph + _mm(7, dpi)
    y = heading("4. WHITE DENSITY  (solid block and fine white strokes)", y)

    # --- white density --------------------------------------------------------
    draw.rectangle([margin, y, margin + _mm(40, dpi), y + ph - 1], fill=WHITE)
    label("SOLID", margin, y + ph + _mm(1, dpi))
    xs = margin + _mm(46, dpi)
    for i, mm_w in enumerate([0.3, 0.5, 0.8, 1.2]):
        t = max(1, _mm(mm_w, dpi))
        x = xs + i * _mm(14, dpi)
        draw.rectangle([x, y, x + t - 1, y + ph - 1], fill=WHITE)
        label(f"{mm_w}", x, y + ph + _mm(1, dpi))
    elements.append("white_density")
    y += ph + _mm(7, dpi)
    y = heading("5. STROKE LADDER  (mm at final print scale)", y)

    # --- stroke ladder --------------------------------------------------------
    line_len = _mm(110, dpi)
    for mm_w in STROKE_LADDER_MM:
        t = max(1, _mm(mm_w, dpi))
        draw.rectangle([margin, y, margin + line_len, y + t - 1], fill=WHITE)
        label(f"{mm_w} mm", margin + line_len + _mm(4, dpi), y - _mm(0.5, dpi))
        regions.setdefault("stroke_ladder", []).append(
            {"mm": mm_w, "thickness_px": t, "x": margin, "y": y, "w": line_len})
        y += t + _mm(4.5, dpi)
    elements.append("stroke_ladder")
    y += _mm(2, dpi)
    y = heading("6. NEGATIVE SPACE / COUNTER TEST  (gap width in mm)", y)

    # --- negative space -------------------------------------------------------
    box = _mm(16, dpi)
    for i, mm_gap in enumerate(NEGATIVE_SPACE_MM):
        x = margin + i * (box + gap)
        draw.rectangle([x, y, x + box - 1, y + box - 1], fill=WHITE)
        g = max(1, _mm(mm_gap, dpi))
        cy = y + box // 2 - g // 2
        draw.rectangle([x, cy, x + box - 1, cy + g - 1], fill=TRANSPARENT)
        label(f"{mm_gap}", x, y + box + _mm(1, dpi))
        regions.setdefault("negative_space_test", []).append(
            {"mm": mm_gap, "gap_px": g, "x": x, "y": y, "box": box,
             "gap_top": cy, "probe_x": x + box // 2})
    elements.append("negative_space_test")
    y += box + _mm(7, dpi)
    y = heading("7. HARD EDGE vs FADE  (left hard, right gradient to transparent)", y)

    # --- hard edge vs fade ----------------------------------------------------
    bw, bh = _mm(55, dpi), _mm(18, dpi)
    draw.rectangle([margin, y, margin + bw, y + bh - 1], fill=WHITE)
    label("HARD", margin, y + bh + _mm(1, dpi))
    fx = margin + bw + _mm(12, dpi)
    grad = Image.new("RGBA", (bw, bh), TRANSPARENT)
    gp = grad.load()
    for px in range(bw):
        a = round(255 * (1 - px / max(1, bw - 1)))
        for py in range(bh):
            gp[px, py] = (255, 255, 255, a)
    canvas.alpha_composite(grad, (fx, y))
    label("FADE", fx, y + bh + _mm(1, dpi))
    elements.append("hard_edge_vs_fade")
    y += bh + _mm(7, dpi)
    y = heading("8. IP STRING FIDELITY  (exact strings only - no interpretation)", y)

    # --- text ladder ----------------------------------------------------------
    for pt in TEXT_LADDER_PT:
        img = render_line(font_path, IP_PROBE_STRING, _pt(pt, dpi), 0)
        canvas.alpha_composite(img, (margin, y))
        rendered.append(IP_PROBE_STRING)
        label(f"{pt}pt", margin + _mm(120, dpi), y)
        y += img.height + _mm(3, dpi)
    tiy = render_line(font_path, "THE INCREDIBLE YOU", _pt(12, dpi), 0)
    canvas.alpha_composite(tiy, (margin, y))
    rendered.append("THE INCREDIBLE YOU")
    label("12pt", margin + _mm(120, dpi), y)
    y += tiy.height + _mm(6, dpi)
    elements.append("ip_text_ladder")
    y = heading("9. 100 mm REFERENCE RULER  (measure after pressing)", y)

    # --- ruler ----------------------------------------------------------------
    ruler_len = _mm(100, dpi)
    bar = max(1, _mm(0.6, dpi))
    draw.rectangle([margin, y, margin + ruler_len, y + bar - 1], fill=WHITE)
    for i in range(11):
        gx = margin + round(ruler_len * i / 10)
        tick = _mm(4 if i % 5 == 0 else 2.5, dpi)
        draw.rectangle([gx, y, gx + bar - 1, y + tick], fill=WHITE)
        if i % 5 == 0:
            label(f"{i * 10}", gx, y + tick + _mm(1, dpi))
    regions["ruler_100mm"] = {"x": margin, "y": y, "length_px": ruler_len,
                              "length_mm": 100.0}
    elements.append("ruler_100mm")
    y += _mm(12, dpi)

    label("SUPPLIED UNMIRRORED - 300 DPI ASSUMED - sRGB ASSUMED - DO NOT RESIZE",
          margin, y)
    y += _mm(6, dpi)

    # --- finalise and add registration marks ---------------------------------
    final_h = y + margin
    canvas = canvas.crop((0, 0, W, final_h))
    draw = ImageDraw.Draw(canvas)

    reg_inset, reg_len, reg_t = _mm(3, dpi), _mm(8, dpi), max(1, _mm(0.5, dpi))
    for cx, cy in ((reg_inset, reg_inset), (W - reg_inset, reg_inset),
                   (reg_inset, final_h - reg_inset), (W - reg_inset, final_h - reg_inset)):
        draw.rectangle([cx - reg_len // 2, cy - reg_t // 2,
                        cx + reg_len // 2, cy + reg_t // 2], fill=WHITE)
        draw.rectangle([cx - reg_t // 2, cy - reg_len // 2,
                        cx + reg_t // 2, cy + reg_len // 2], fill=WHITE)
    elements.append("registration_marks")

    all_chars = "".join(set("".join(rendered)))
    return CalibrationResult(
        image=canvas,
        width_mm=width_mm,
        height_mm=final_h / dpi * 25.4,
        dpi=dpi,
        elements=elements,
        rendered_strings=sorted(set(rendered)),
        missing_glyph_chars=missing_glyphs(font_path, all_chars),
        regions=regions,
    )
